version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    working_dir: /app
    entrypoint: ["java", "-jar", "/app/target/MarkPriceController-0.0.1-SNAPSHOT.jar", "--debug"]
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge